name: Build CalculatorOS ISO

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y nasm gcc-multilib build-essential genisoimage xorriso mtools
      - run: make all
      - run: |
          mkdir -p build/iso
          gcc -m32 -c boot/bootloader.S -o build/boot.o
          ld -m elf_i386 -Ttext 0x7c00 --oformat binary build/boot.o -o build/boot.bin
          cp build/boot.bin build/iso/boot.bin
          cp build/kernel.bin build/iso/kernel.bin
      - run: mkisofs -o build/calcos.iso -b boot.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table build/iso
      - uses: actions/upload-artifact@v4
        with:
          name: CalculatorOS-ISO
          path: build/calcos.iso
